[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "nodePackages.pnpm"]

[phases.install]
cmds = ["cd /app && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd /app && pnpm --filter @blubranch/db exec prisma generate"]

[start]
cmd = "cd /app/packages/api && npx prisma migrate deploy --schema=../db/prisma/schema.prisma && node --import tsx src/server.ts"
